use_frameworks!

target 'MTCoordinatorView-objc_Example' do
  pod 'MTCoordinatorView-objc', :path => '../'

  target 'MTCoordinatorView-objc_Tests' do
    inherit! :search_paths

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  
  pod 'libextobjc', '~> 0.4'
  end
end
